// Code-level recruitment constants. DB migrations may still use varchar/check constraints.
export enum JobDescriptionStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum JobDescriptionVersionStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  SUPERSEDED = 'SUPERSEDED',
  ARCHIVED = 'ARCHIVED',
}

export enum JobPostingStatus {
  DRAFT = 'DRAFT',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  PUBLISH_FAILED = 'PUBLISH_FAILED',
  MANUAL_REQUIRED = 'MANUAL_REQUIRED',
  CLOSED = 'CLOSED',
}

export enum RecruitmentChannel {
  VCS_PORTAL = 'VCS_PORTAL',
  FACEBOOK = 'FACEBOOK',
  LINKEDIN = 'LINKEDIN',
  TOPCV = 'TOPCV',
  VIETNAMWORKS = 'VIETNAMWORKS',
  MANUAL = 'MANUAL',
  OTHER = 'OTHER',
}

export enum ChannelPostingStatus {
  DRAFT = 'DRAFT',
  PUBLISHING = 'PUBLISHING',
  PUBLISHED = 'PUBLISHED',
  PUBLISH_FAILED = 'PUBLISH_FAILED',
  MANUAL_REQUIRED = 'MANUAL_REQUIRED',
  UPDATED = 'UPDATED',
  CLOSED = 'CLOSED',
}

export enum ChannelIngestionStatus {
  RECEIVED = 'RECEIVED',
  NORMALIZED = 'NORMALIZED',
  APPLICATION_CREATED = 'APPLICATION_CREATED',
  DUPLICATE_DETECTED = 'DUPLICATE_DETECTED',
  CV_FETCH_PENDING = 'CV_FETCH_PENDING',
  CV_FETCH_FAILED = 'CV_FETCH_FAILED',
  FAILED = 'FAILED',
}

export enum ChannelCapabilityStatus {
  SUPPORTED = 'SUPPORTED',
  TBD = 'TBD',
  MANUAL_REQUIRED = 'MANUAL_REQUIRED',
  LATER = 'LATER',
  NOT_SUPPORTED = 'NOT_SUPPORTED',
}

export enum ChannelAccountStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum ApplicationSourceType {
  PORTAL = 'PORTAL',
  CHANNEL = 'CHANNEL',
  MANUAL_IMPORT = 'MANUAL_IMPORT',
  WEBHOOK = 'WEBHOOK',
  EMAIL_PARSE = 'EMAIL_PARSE',
  OTHER = 'OTHER',
}

export enum ApplicationStatus {
  APPLICATION_CREATED = 'APPLICATION_CREATED',
  APPLICATION_VALIDATING = 'APPLICATION_VALIDATING',
  APPLICATION_REJECTED_INVALID = 'APPLICATION_REJECTED_INVALID',
  APPLICATION_DUPLICATE_CHECKING = 'APPLICATION_DUPLICATE_CHECKING',
  APPLICATION_DUPLICATE_FOUND = 'APPLICATION_DUPLICATE_FOUND',
  APPLICATION_OVERWRITTEN = 'APPLICATION_OVERWRITTEN',
  APPLICATION_REJECTED_RATE_LIMIT = 'APPLICATION_REJECTED_RATE_LIMIT',
  CV_UPLOADED = 'CV_UPLOADED',
  CV_STORED_QUARANTINE = 'CV_STORED_QUARANTINE',
  CV_SCAN_REQUESTED = 'CV_SCAN_REQUESTED',
  CV_SCAN_PASSED = 'CV_SCAN_PASSED',
  CV_REJECTED_MALWARE = 'CV_REJECTED_MALWARE',
  CV_SANITIZING = 'CV_SANITIZING',
  CV_SANITIZED = 'CV_SANITIZED',
  CV_SANITIZE_FAILED = 'CV_SANITIZE_FAILED',
  CV_PARSED = 'CV_PARSED',
  PROFILE_DUPLICATE_CHECKED = 'PROFILE_DUPLICATE_CHECKED',
  PROFILE_DUPLICATE_NEEDS_REVIEW = 'PROFILE_DUPLICATE_NEEDS_REVIEW',
  MAPPING_REQUESTED = 'MAPPING_REQUESTED',
  MAPPING_DONE = 'MAPPING_DONE',
  MAPPING_FAILED = 'MAPPING_FAILED',
  MAPPING_REJECTED = 'MAPPING_REJECTED',
  ELIGIBLE_FOR_FORM = 'ELIGIBLE_FOR_FORM',
  FORM_SESSION_CREATED = 'FORM_SESSION_CREATED',
  FORM_SENT = 'FORM_SENT',
  FORM_OPENED = 'FORM_OPENED',
  FORM_SUBMITTED = 'FORM_SUBMITTED',
  FORM_EXPIRED = 'FORM_EXPIRED',
  AI_SCREENING_REQUESTED = 'AI_SCREENING_REQUESTED',
  AI_SCREENING_DONE = 'AI_SCREENING_DONE',
  AI_SCREENING_FAILED = 'AI_SCREENING_FAILED',
  WAITING_HR_REVIEW = 'WAITING_HR_REVIEW',
  HR_APPROVED = 'HR_APPROVED',
  HR_REJECTED = 'HR_REJECTED',
  HR_REQUESTED_MORE_INFO = 'HR_REQUESTED_MORE_INFO',
  TALENT_POOL = 'TALENT_POOL',
}

export const TERMINAL_APPLICATION_STATUSES = [
  ApplicationStatus.APPLICATION_REJECTED_INVALID,
  ApplicationStatus.APPLICATION_REJECTED_RATE_LIMIT,
  ApplicationStatus.CV_REJECTED_MALWARE,
  ApplicationStatus.MAPPING_REJECTED,
  ApplicationStatus.HR_APPROVED,
  ApplicationStatus.HR_REJECTED,
  ApplicationStatus.TALENT_POOL,
] as const;

export enum CvDocumentType {
  ORIGINAL = 'ORIGINAL',
  CLEAN = 'CLEAN',
}

export enum StorageZone {
  QUARANTINE = 'QUARANTINE',
  SAFE = 'SAFE',
}

export enum CvScanStatus {
  PENDING = 'PENDING',
  SCANNING = 'SCANNING',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  REJECTED_MALWARE = 'REJECTED_MALWARE',
}

export enum CvSanitizeStatus {
  PENDING = 'PENDING',
  SANITIZING = 'SANITIZING',
  SANITIZED = 'SANITIZED',
  FAILED = 'FAILED',
}

export enum CvParseStatus {
  PENDING = 'PENDING',
  PARSING = 'PARSING',
  PARSED = 'PARSED',
  FAILED = 'FAILED',
}

export enum DuplicateCheckType {
  APPLICATION_EMAIL_PHONE_JD = 'APPLICATION_EMAIL_PHONE_JD',
  CV_FILE_HASH = 'CV_FILE_HASH',
  PARSED_PROFILE = 'PARSED_PROFILE',
}

export enum DuplicateCheckStatus {
  PASSED = 'PASSED',
  DUPLICATE_FOUND = 'DUPLICATE_FOUND',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  FAILED = 'FAILED',
}

export enum MappingStatus {
  REQUESTED = 'REQUESTED',
  DONE = 'DONE',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
}

export enum MappingRecommendation {
  PASS = 'PASS',
  REJECT = 'REJECT',
  TALENT_POOL = 'TALENT_POOL',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum QuestionSetStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum FormSessionStatus {
  CREATED = 'CREATED',
  SENT = 'SENT',
  OPENED = 'OPENED',
  SUBMITTED = 'SUBMITTED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum AiScreeningStatus {
  REQUESTED = 'REQUESTED',
  DONE = 'DONE',
  FAILED = 'FAILED',
}

export enum AiScreeningRecommendation {
  WAITING_HR_REVIEW = 'WAITING_HR_REVIEW',
  STRONG_MATCH = 'STRONG_MATCH',
  MATCH = 'MATCH',
  NEEDS_HR_REVIEW = 'NEEDS_HR_REVIEW',
  WEAK_MATCH = 'WEAK_MATCH',
  REJECT_RECOMMENDED = 'REJECT_RECOMMENDED',
  TALENT_POOL_RECOMMENDED = 'TALENT_POOL_RECOMMENDED',
}

export enum HrReviewDecisionType {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  REQUEST_MORE_INFO = 'REQUEST_MORE_INFO',
  TALENT_POOL = 'TALENT_POOL',
}

export enum ConversationStatus {
  OPEN = 'OPEN',
  BOT_ACTIVE = 'BOT_ACTIVE',
  NEEDS_HR_HANDOFF = 'NEEDS_HR_HANDOFF',
  HR_TAKEOVER = 'HR_TAKEOVER',
  HANDOFF = 'HANDOFF',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum MessageDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
}

export enum ChannelMessageSenderType {
  CANDIDATE = 'CANDIDATE',
  BOT = 'BOT',
  HR = 'HR',
  SYSTEM = 'SYSTEM',
}

export enum ChannelMessageType {
  TEXT = 'TEXT',
  FILE = 'FILE',
  LINK = 'LINK',
  EVENT = 'EVENT',
}

export enum BotKnowledgeSourceType {
  JOB_DESCRIPTION = 'JOB_DESCRIPTION',
  JOB_POSTING = 'JOB_POSTING',
  FAQ = 'FAQ',
  POLICY = 'POLICY',
}

export enum BotKnowledgeStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}
